name: Update Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "7 */6 * * *"  # every 6 hours at :07 past (UTC)

permissions:
  contents: write

concurrency:
  group: update-calendar
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build ICS
        run: python scripts/build_poole_u18_ics.py

      - name: Commit and push updated files
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add poole_town_u18_colts_fixtures.ics .state_poole_u18.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update ICS from FullTimeAPI"
            git push
          fi


       - name: Send Telegram alert if changes
         if: success()
         env:
           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         run: |
           if [ -s notify.txt ] && [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_ID" ]; then
             echo "Sending Telegram notification…"
             TEXT="$(cat notify.txt)"
             curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
               --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
               --data-urlencode "text=${TEXT}" \
               --data-urlencode "parse_mode=HTML" \
               > /dev/null
           else
             echo "No notification to send or Telegram secrets not set."
           fi
      
       - name: Clean up notify.txt
         if: always()
         run: |
           if [ -f notify.txt ]; then rm notify.txt; fi
