name: Update Calendar

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 4 AM UTC
  workflow_dispatch:      # Also allows manual run from GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests ics pytz

      - name: Generate .ics file
        run: python generate_calendar.py

      - name: Commit and push updated .ics
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add poole_town_u18_colts_fixtures.ics
          git commit -m "Daily update" || echo "No changes"
          git push
